import pandas as pd

#.csv file would be autogenerated every hour from on-field sensors that generate the data.
data = pd.read_csv("insurance.csv")

#SeismicWaveAmplitude_nm is the seismic wave amplitude in nanometers.
##SeismicFrequency_Hz is the seismic frequency in hertz.
#SeismicVelocity_m_s is the seismic velocity in meters per second.
#ElectricalChange_uV is the electrical change in microvolts.
#GroundWaterChange_m is the ground water change in meters.
#AnimalActivityDuration_h is the length of animal activity in hours.